# Generated by Django 2.2.7 on 2019-11-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('short', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.List')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSubscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.Subscription')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.User')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='idOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='listownik.User'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='idSubscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subscriber', to='listownik.User'),
        ),
        migrations.CreateModel(
            name='Shop_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.Product')),
                ('idShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='idShop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.Shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='idType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.Measure'),
        ),
        migrations.CreateModel(
            name='List_Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.List')),
                ('idSubscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='List_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBought', models.BooleanField(default=False)),
                ('idList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.List')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.Product')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='idOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listownik.User'),
        ),
    ]
